/*
 * Import form that allow you to select Location and Flight files to import tot eh Location and Flight tables respectively
 */
package uflybookingsystem.Forms;


import java.io.InputStream;
import javax.swing.JFileChooser;
import uflybookingsystem.ImportResult;

//import uflybookingsystem.UFlyBookingSystem.


public class ImportForm extends javax.swing.JFrame {

    /**
     * Creates new form ImportForm
     */
    
    //variable for file name
    String fileName = "";

    
    InputStream in = null;
    public ImportForm() {
        initComponents();
        
        //setting bounds of frame
        this.setBounds(100,100,600,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        txtFlights = new javax.swing.JTextField();
        btnImportFlights = new javax.swing.JButton();
        txtLocations = new javax.swing.JTextField();
        btnImportLocations = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBrowseFlight = new javax.swing.JButton();
        btnBrowseLocation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Import Files");

        txtFlights.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFlights.setName(""); // NOI18N
        txtFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlightsActionPerformed(evt);
            }
        });

        btnImportFlights.setBackground(new java.awt.Color(255, 153, 153));
        btnImportFlights.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImportFlights.setForeground(new java.awt.Color(0, 51, 255));
        btnImportFlights.setText("Import Flights");
        btnImportFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportFlightsActionPerformed(evt);
            }
        });

        txtLocations.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLocations.setText("C:/Users/91030283/Desktop/Locations.txt");

        btnImportLocations.setBackground(new java.awt.Color(255, 153, 153));
        btnImportLocations.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImportLocations.setForeground(new java.awt.Color(0, 51, 255));
        btnImportLocations.setText("Import Locations");
        btnImportLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportLocationsActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 153, 153));
        btnClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(0, 51, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Select Locations File:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Select Flights File:");

        btnBrowseFlight.setBackground(new java.awt.Color(255, 153, 153));
        btnBrowseFlight.setForeground(new java.awt.Color(0, 51, 255));
        btnBrowseFlight.setText("Browse");
        btnBrowseFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseFlightActionPerformed(evt);
            }
        });

        btnBrowseLocation.setBackground(new java.awt.Color(255, 153, 153));
        btnBrowseLocation.setForeground(new java.awt.Color(0, 51, 255));
        btnBrowseLocation.setText("Browse");
        btnBrowseLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnClose)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnImportFlights, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowseFlight))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnImportLocations)
                                    .addComponent(txtLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowseLocation)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseLocation))
                .addGap(24, 24, 24)
                .addComponent(btnImportLocations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseFlight))
                .addGap(24, 24, 24)
                .addComponent(btnImportFlights)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //this method allows you to select the Location text file.
    //File's path should appear in the txtLocations 
    private void btnBrowseLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseLocationActionPerformed

        JFileChooser fc = new JFileChooser();
        int i = fc.showDialog(this, null);
        fileName =  fc.getSelectedFile().toString();
        txtLocations.setText(fileName);
        
    }//GEN-LAST:event_btnBrowseLocationActionPerformed
    
    //this method allows you to select the Flight text file.
    //File's path should appear in the txtFlights
    private void btnBrowseFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseFlightActionPerformed
        
        JFileChooser fc = new JFileChooser();
        int i = fc.showDialog(this, null);
        fileName =  fc.getSelectedFile().toString();
        txtFlights.setText(fileName);
        
        
        
        
    }//GEN-LAST:event_btnBrowseFlightActionPerformed

    //Location Import button action. Creates new instance of the LocationImporter
    //and calls it's run() method
    //Then the ImportFeedbackForm instance is created and displayed to see the result of the import
    private void btnImportLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportLocationsActionPerformed

        LocationImporter locImp = new LocationImporter(fileName);
        Thread thread = new Thread(locImp);
        thread.start();
        //thread.wait(2000);
        ImportFeedbackForm impFeedbackForm = new ImportFeedbackForm(locImp.getResults());
        
    }//GEN-LAST:event_btnImportLocationsActionPerformed

    //Location Import button action. Creates new instance of the LocationImporter
    //and calls it's run() method
    //Then the ImportFeedbackForm instance is created and displayed to see the result of the import
    private void btnImportFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportFlightsActionPerformed
        
        FlightImporter flightImp = new FlightImporter(fileName);
        Thread thread = new Thread(flightImp);
        thread.start();
        //thread.wait(2000);
        ImportFeedbackForm impFeedbackForm = new ImportFeedbackForm(flightImp.getResults());
    }//GEN-LAST:event_btnImportFlightsActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseFlight;
    private javax.swing.JButton btnBrowseLocation;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnImportFlights;
    private javax.swing.JButton btnImportLocations;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFlights;
    private javax.swing.JTextField txtLocations;
    // End of variables declaration//GEN-END:variables
}
